import { expect, test } from '@playwright/test';
import { join } from 'node:path';

// Full click-through of the storyboard importer through a real <input type="file"> upload —
// the one part of this feature the unit tests (which call handleFile() directly, or drive a
// jsdom change event) can't exercise, since a real browser is what makes setInputFiles()
// meaningful. Fixtures generated by scripts/_gen-e2e-docx-fixtures.mjs (run once, then deleted)
// and tests/fixtures/storyboard/valid-template.docx (the real, still-unfilled template).

const fixture = name => join(process.cwd(), 'tests', 'fixtures', 'storyboard', name);

async function openStoryboardImporter(page) {
  await page.goto('/?dashboard');
  await page.locator('#starter-action-storyboard').click();
  await expect(page.locator('#sbi-file-input')).toBeAttached();
}

test('a non-.docx file reaches the parse-error step, and "choose a different file" recovers', async ({ page }) => {
  await openStoryboardImporter(page);
  await page.locator('#sbi-file-input').setInputFiles(fixture('e2e-not-a-docx.docx'));

  await expect(page.getByText(/could not import/i)).toBeVisible();
  await page.locator('#sbi-retry-btn').click();
  await expect(page.locator('#sbi-file-input')).toBeAttached();
});

test('the real (unfilled) template shows its fatal findings and Confirm stays disabled', async ({ page }) => {
  await openStoryboardImporter(page);
  await page.locator('#sbi-file-input').setInputFiles(fixture('valid-template.docx'));

  await expect(page.getByText(/must be fixed before this can be imported/i)).toBeVisible();
  await expect(page.locator('#sbi-confirm-btn')).toBeDisabled();
  // The template's own bracketed placeholder example row is surfaced, not silently dropped.
  await expect(page.getByText(/S01-B07/).first()).toBeVisible();
});

test('a fully filled-in storyboard imports end to end: review, confirm, and land in the new course workspace', async ({ page }) => {
  await openStoryboardImporter(page);
  await page.locator('#sbi-file-input').setInputFiles(fixture('e2e-valid-filled.docx'));

  await expect(page.locator('#sbi-project-name')).toHaveValue('Warehouse Safety Basics');
  await expect(page.locator('#sbi-confirm-btn')).toBeEnabled();
  await expect(page.getByText('S01-B01')).toBeVisible();
  await expect(page.getByText('S01-B02')).toBeVisible();

  await page.locator('#sbi-confirm-btn').click();

  const overview = page.locator('#project-overview-workspace');
  await expect(overview).toBeVisible();
  await expect(overview.locator('.workspace-title')).toContainText('Warehouse Safety Basics');

  // The BUILDER row (Accordion) keeps its Focus Edit control; the RISE row does not.
  const rows = overview.locator('.component-row');
  await expect(rows).toHaveCount(2);
  const riseRow = rows.filter({ hasText: 'Rise: Text' });
  await expect(riseRow).toBeVisible();
  await expect(riseRow.locator('[data-action="edit-comp"]')).toHaveCount(0);
  const builderRow = rows.filter({ hasText: 'Accordion' });
  await expect(builderRow.locator('[data-action="edit-comp"]')).toHaveCount(1);

  // The Rise build sheet action appears now that the course has a RISE row.
  await expect(page.locator('#wp-rise-sheet-btn')).toBeVisible();
  await page.locator('#wp-rise-sheet-btn').click();
  await expect(page.locator('#pmi-rise-sheet-text')).toContainText('S01-B01');
  await expect(page.locator('#pmi-rise-sheet-text')).not.toContainText('Key principles');
});

test('the real all-26-component-types template uploads and reviews through the actual UI, mapping every BUILDER row to its real type', async ({ page }) => {
  await openStoryboardImporter(page);
  await page.locator('#sbi-file-input').setInputFiles(fixture('all-components-template.docx'));

  const importer = page.locator('#storyboard-import-workspace');

  // Parsed and reviewed, not stuck on the parse-error step — proves the real upload path
  // handles a large, real, multi-section document with every supported component type.
  await expect(page.locator('#sbi-project-name')).toHaveValue('Fiber Deployment Readiness');
  await expect(importer.getByText('4 sections')).toBeVisible();

  // A representative sample of the 26 types, each shown with its real block type badge.
  for (const blockType of ['Accordion', 'Study Cards', 'Hotspots', 'Multiple Select', 'Scenario', 'Interactive Video', 'Confidence Matrix']) {
    await expect(importer.getByText(blockType, { exact: true }).first()).toBeVisible();
  }

  // The template's own 2 genuine content gaps (see all-components-field-mapping.test.js) are
  // surfaced, not silently accepted — Confirm correctly stays disabled for this exact file.
  await expect(importer.getByText(/must be fixed before this can be imported/i)).toBeVisible();
  await expect(page.locator('#sbi-confirm-btn')).toBeDisabled();
});
